services:
  - type: web
    name: laravel-app
    runtime: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: ""
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://recommandation-api-b8un.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ""
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        value: ""
      - key: DB_USERNAME
        value: ""
      - key: DB_PASSWORD
        value: ""
